// This file is automatically generated by Firebase Studio. Do not edit manually.

export const firebaseConfig = {
  "apiKey": "AIzaSyAbIedH-hRC1QH5lAatDMT31eZa5TtkSWo",
  "authDomain": "ghana-trade-insights.firebaseapp.com",
  "projectId": "ghana-trade-insights",
  "storageBucket": "ghana-trade-insights.appspot.com",
  "messagingSenderId": "995638966989",
  "appId": "1:995638966989:web:d1908cedbc8032ee818784"
};
